Repository 6-dreaming-stars/space-star-front-monorepo, pull requests merged in 2024-06, with the labels that each got.

#20 Feature/sign up
  .eslintrc.json
  package.json
  packages/web/.env.example
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/apis/createUser.ts
  packages/web/src/app/@modal/(.)sign-in/page.tsx
  packages/web/src/app/@modal/(.)sign-up/page.tsx
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/api/auth/[...nextauth]/route.ts
  packages/web/src/app/auth-error/page.tsx
  packages/web/src/app/page.tsx
  packages/web/src/app/test/page.tsx
  packages/web/src/components/DatePicker/DatePicker.tsx
  packages/web/src/components/Navbar/index.tsx
  packages/web/src/components/modal/modal.tsx
  packages/web/src/components/sign/SignButton.tsx
  packages/web/src/components/sign/sign.module.css
  packages/web/src/components/ui/calendar.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/types/next-auth.d.ts
  packages/web/tsconfig.json
  yarn.lock
Labels: ✨ Feature, gpt review

#21 Fix: searchParams 설정 추가
  packages/web/next.config.mjs
Labels: 🐞 BugFix

#22 Feature/sign up
  packages/ui/src/components/Inputs/Checkbox.tsx
  packages/ui/src/components/Inputs/Input.tsx
  packages/ui/src/components/Inputs/Select.tsx
  packages/ui/tsconfig.tsbuildinfo
  packages/web/src/apis/createUser.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/page.tsx
  packages/web/src/components/Navbar/index.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/types/next-auth.d.ts
Labels: ✨ Feature, gpt review

#23 Feature/sign up
  packages/ui/src/components/Icons/Bot.tsx
  packages/web/public/images/emoji/emoji_svg_1.svg
  packages/web/public/images/emoji/emoji_svg_3.svg
  packages/web/src/apis/auth.ts
  packages/web/src/apis/createUser.ts
  packages/web/src/app/@modal/(.)additional-info/page.tsx
  packages/web/src/app/additional-info/page.tsx
  packages/web/src/app/auth/callback/page.tsx
  packages/web/src/app/auth/popup/page.tsx
  packages/web/src/components/DatePicker/DatePicker.tsx
  packages/web/src/components/Navbar/LoginButton.tsx
  packages/web/src/components/form/formLayout.tsx
  packages/web/src/components/modal/fakeModal.tsx
  packages/web/src/components/modal/modal.tsx
  packages/web/src/components/sign/SignButton.tsx
  packages/web/src/components/sign/SignLayout.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/additional-info/AdditionalInfoLayout.tsx
  packages/web/src/containers/sign-in/SignInLayout.tsx
  packages/web/src/containers/sign-up/SignUpLayout.tsx
  packages/web/src/hooks/fetchWithToken.ts
Labels: 📬 API, ✨ Feature, gpt review

#27 컴포넌트 UI
  packages/ui/src/components/Games/GameListButton.stories.tsx
  packages/ui/src/components/Games/GameListButton.tsx
  packages/ui/src/components/Games/game.css
  packages/ui/src/components/Icons/Logo.stories.ts
  packages/ui/src/components/Icons/Logo.tsx
  packages/ui/src/components/Icons/Search.stories.tsx
  packages/ui/src/components/Icons/Search.tsx
  packages/ui/src/components/Icons/Star.stories.tsx
  packages/ui/src/components/Icons/Star.tsx
  packages/ui/src/components/Icons/ViewCard.stories.tsx
  packages/ui/src/components/Icons/ViewCard.tsx
  packages/ui/src/components/Icons/ViewList.stories.tsx
  packages/ui/src/components/Icons/ViewList.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/Inputs/Input.css
  packages/ui/src/components/Inputs/SearchInput.stories.tsx
  packages/ui/src/components/Inputs/SearchInput.tsx
  packages/ui/src/components/Inputs/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
Labels: 🎨 Html&css

#28 Feature/team list
  packages/ui/src/components/Icons/Logo.tsx
  packages/ui/src/components/Icons/LogoName.tsx
  packages/ui/src/components/Icons/Search.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/src/apis/game.ts
  packages/web/src/apis/member.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/auth/callback/page.tsx
  packages/web/src/app/auth/error/page.tsx
  packages/web/src/app/auth/popup/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/dashboard/team-list/state.ts
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  packages/web/src/app/team-list/page.tsx
  packages/web/src/components/Navbar/Navbar.module.css
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/index.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/components/sign/SignButton.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/SubSelectBox.tsx
  packages/web/src/containers/team-list/SubSelectButtons.tsx
  packages/web/src/containers/team-list/TeamBox.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/styles/globals.css
Labels: ✨ Feature, 🎨 Html&css, gpt review

#31 Feature/chat component
  packages/ui/src/components/Avatar/Avatar.tsx
  packages/ui/src/components/Icons/EmojiIcon.tsx
  packages/ui/src/components/Icons/FileIcon.tsx
  packages/ui/src/components/Icons/SendIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/src/apis/chat.ts
  packages/web/src/apis/friends.ts
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/chat/tmp.css
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/app/dashboard/team-list/layout.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Friends/friends.module.css
  packages/web/src/components/Navbar/Navbar.module.css
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/NavbarItem.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/chat/ChatInputBox.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/SearchBox.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/styles/colors.css
  packages/web/src/styles/globals.css
  packages/web/src/types/next-auth.d.ts
Labels: ✨ Feature, 🎨 Html&css, gpt review

#33 Feature/size style
  packages/web/src/app/(auth)/additional-info/page.tsx
  packages/web/src/app/(auth)/sign-in/page.tsx
  packages/web/src/app/(auth)/sign-up/page.tsx
  packages/web/src/app/@modal/(.)additional-details/page.tsx
  packages/web/src/app/@modal/(.)sign-in/page.tsx
  packages/web/src/app/@modal/(.)sign-up/page.tsx
  packages/web/src/components/modal/fakeModal.tsx
  packages/web/src/components/modal/modal.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/LikeGameForm.tsx
Labels: 🎨 Html&css

#37 Chore: update yarn.lock
  yarn.lock
Labels: 🌏 Deploy

#38 FIX/auth
  packages/web/src/apis/createUser.ts
  packages/web/src/apis/game.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/team-list/layout.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/SelectBoxContainer.tsx
Labels: 🐞 BugFix, gpt review

#40 Mail Merge
  packages/ui/src/components/Games/GameListButton.tsx
  packages/web/src/apis/createUser.ts
  packages/web/src/apis/game.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/team-list/layout.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/SelectBoxContainer.tsx
  packages/web/src/containers/team-list/state.ts
  packages/web/src/containers/team-list/teamList.module.css
  yarn.lock
Labels: 🌏 Deploy

#41 Feature/game fetch
  .eslintrc.json
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  package.json
  packages/ui/src/components/Games/GameListButton.tsx
  packages/ui/src/components/Games/game.css
  packages/ui/src/components/Icons/CirclePlus.tsx
  packages/ui/src/components/Inputs/select.css
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/apis/game.ts
  packages/web/src/apis/profile.ts
  packages/web/src/apis/state.ts
  packages/web/src/app/@modal/(.)additional-details/page.tsx
  packages/web/src/app/additional-details/page.tsx
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  packages/web/src/app/test/page.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/form/formLayout.tsx
  packages/web/src/components/game/GameSelectBox.tsx
  packages/web/src/components/modal/modalClient.tsx
  packages/web/src/components/providers/modal-provider.tsx
  packages/web/src/components/ui/alert.tsx
  packages/web/src/components/ui/select.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalGames.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/additional-details/AdditionalOptions.tsx
  packages/web/src/containers/additional-details/LikeGameForm.tsx
  packages/web/src/containers/additional-details/MBTIForm.tsx
  packages/web/src/containers/additional-details/action.ts
  packages/web/src/containers/additional-details/additional.module.css
  packages/web/src/containers/additional-details/state.ts
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/store/gameStore.ts
  packages/web/src/styles/colors.css
  packages/web/src/styles/globals.css
  packages/web/src/types/next-auth.d.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css, gpt review

#43 Feature/refactor
  package.json
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/public/images/opengraph-image.png
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/home/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/app/test/page.tsx
  packages/web/src/components/Gutter/index.tsx
  packages/web/src/components/Navbar/Navbar.module.css
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/NavbarItem.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/components/game/GameSelectBox.tsx
  packages/web/src/components/providers/socket-provider.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/additional-details/action.ts
  packages/web/src/containers/chat/ChatInputBox.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/styles/globals.css
  yarn.lock
Labels: 🔨 Refactor, 🥰 Accessibility

#45 Feature/style
  packages/ui/src/components/Card/FlipCard.stories.ts
  packages/ui/src/components/Card/FlipCard.tsx
  packages/ui/src/components/Card/card.css
  packages/ui/src/components/Icons/Theme.tsx
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Friends/OnlineFriends.tsx
  packages/web/src/components/Friends/_FriendsList.tsx
  packages/web/src/components/Friends/friends.module.css
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/hooks/useDrag.tsx
Labels: 🎨 Html&css, gpt review

#46 Rename: 오타 및 변수명 수정
  packages/ui/src/components/Card/FlipCard.tsx
  packages/web/src/components/Friends/friends.module.css
Labels: 🎨 Html&css

#48 Feature/chat
  packages/ui/src/components/Games/GameOption.tsx
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/src/apis/auth-member.ts
  packages/web/src/apis/chat.ts
  packages/web/src/apis/member.ts
  packages/web/src/apis/profileImage.ts
  packages/web/src/apis/state.ts
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/chat/tmp.css
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/providers/socket-provider.tsx
  packages/web/src/containers/chat-room/ChatLogList.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/chat-room/chat.module.css
  packages/web/src/containers/chat/ChatInputBox.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/MessageItem.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/hooks/convertToLocaleTime.ts
  packages/web/src/styles/globals.css
  packages/web/src/types/ChatType.ts
Labels: ✨ Feature, 🎨 Html&css, gpt review

#51 Feature/seo
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next-sitemap.config.js
  packages/web/package.json
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  yarn.lock
Labels: 🥰 Accessibility

#52 Production Build
  packages/ui/src/components/Games/GameOption.tsx
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next-sitemap.config.js
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/apis/auth-member.ts
  packages/web/src/apis/chat.ts
  packages/web/src/apis/member.ts
  packages/web/src/apis/profileImage.ts
  packages/web/src/apis/state.ts
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/chat/tmp.css
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/providers/socket-provider.tsx
  packages/web/src/containers/chat-room/ChatLogList.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/chat-room/chat.module.css
  packages/web/src/containers/chat/ChatInputBox.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/MessageItem.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/hooks/convertToLocaleTime.ts
  packages/web/src/styles/globals.css
  packages/web/src/types/ChatType.ts
  yarn.lock
Labels: 🌏 Deploy

#53 Chore: 타입 설치
  packages/ui/package.json
  packages/ui/tsconfig.json
  yarn.lock
Labels: 🌏 Deploy

#54 Fix: sitemap 수정
  packages/ui/tsconfig.json
  packages/web/next-sitemap.config.js
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/app/robots.ts
  packages/web/src/app/sitemap.ts
Labels: 🌏 Deploy

#55 Build
  .dockerignore
  package.json
  packages/ui/package.json
  yarn.lock
Labels: 🌏 Deploy

#57 Feature/profile s3
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/public/images/default-image.jpg
  packages/web/src/apis/auth-member.ts
  packages/web/src/apis/auth.ts
  packages/web/src/apis/createProfileImage.ts
  packages/web/src/apis/createUser.ts
  packages/web/src/apis/data.ts
  packages/web/src/apis/profile.ts
  packages/web/src/apis/profileImage.ts
  packages/web/src/app/api/_s3.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/DatePicker/DatePicker.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Toast/toast.tsx
  packages/web/src/components/form/form.module.css
  packages/web/src/components/sign/sign.module.css
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/additional-details/action.ts
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/my-page/ProfileImageUpload.tsx
  packages/web/src/lib/uploadFromUrl.ts
  packages/web/src/types/AuthType.ts
  packages/web/src/types/next-auth.d.ts
  yarn.lock
Labels: 📬 API, ✨ Feature, gpt review

#58 Build Test
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/public/images/default-image.jpg
  packages/web/src/apis/auth-member.ts
  packages/web/src/apis/auth.ts
  packages/web/src/apis/createProfileImage.ts
  packages/web/src/apis/createUser.ts
  packages/web/src/apis/data.ts
  packages/web/src/apis/profile.ts
  packages/web/src/apis/profileImage.ts
  packages/web/src/app/api/_s3.ts
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/DatePicker/DatePicker.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Toast/toast.tsx
  packages/web/src/components/form/form.module.css
  packages/web/src/components/sign/sign.module.css
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/additional-details/action.ts
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/my-page/ProfileImageUpload.tsx
  packages/web/src/lib/uploadFromUrl.ts
  packages/web/src/types/AuthType.ts
  packages/web/src/types/next-auth.d.ts
  yarn.lock
Labels: 🌏 Deploy

#61 Update Dockerignore
  .dockerignore
  packages/ui/tsconfig.tsbuildinfo
  yarn.lock
Labels: 🌏 Deploy

#63 Feature/swipe
  packages/web/src/apis/data.ts
  packages/web/src/apis/member.ts
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/dashboard/swipe/page.tsx
  packages/web/src/components/Card/SwipeCard.tsx
  packages/web/src/components/Card/card.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/search/SearchUserBox.tsx
  packages/web/src/containers/swipe/RefreshButton.tsx
  packages/web/src/containers/swipe/SwipeCardWrapper.tsx
  packages/web/src/containers/swipe/swipe.module.css
Labels: 🎨 Html&css

#65 Build Test
  .dockerignore
  Dockerfile
  packages/web/src/apis/auth-sign.ts
  packages/web/src/apis/createProfile.ts
  packages/web/src/apis/data.ts
  packages/web/src/apis/friends.ts
  packages/web/src/apis/getAuth.ts
  packages/web/src/apis/getFriends.ts
  packages/web/src/apis/getMember.ts
  packages/web/src/apis/getProfile.ts
  packages/web/src/apis/getProfileByUuid.ts
  packages/web/src/apis/getProfileImage.ts
  packages/web/src/apis/profile.ts
  packages/web/src/apis/profileImage.ts
  packages/web/src/apis/updateFriends.ts
  packages/web/src/app/@modal/(.)profile/[id]/page.tsx
  packages/web/src/app/api/auth/[...nextauth]/options.ts
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/dashboard/swipe/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/app/profile/[id]/page.tsx
  packages/web/src/components/Card/SwipeCard.tsx
  packages/web/src/components/Card/card.module.css
  packages/web/src/components/Friends/OnlineFriends.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/profile-modal/profileLayout.tsx
  packages/web/src/containers/search/SearchUserContainer.tsx
  packages/web/src/containers/swipe/RefreshButton.tsx
  packages/web/src/containers/swipe/SwipeCardWrapper.tsx
  packages/web/src/containers/swipe/swipe.module.css
  packages/web/src/lib/getAllProfileData.ts
  packages/web/src/store/defaultState.ts
  packages/web/src/types/type.ts
Labels: 🌏 Deploy

#66 Feature/friends
  packages/web/next.config.mjs
  packages/web/src/apis/getFriends.ts
  packages/web/src/app/api/_s3.ts
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Friends/FriendsWrapper.tsx
  packages/web/src/components/Friends/OnlineFriends.tsx
  packages/web/src/components/Friends/_FriendsList.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/NavbarItem.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/lib/getFriendsData.ts
  packages/web/src/lib/getUserData.ts
  packages/web/src/lib/uploadFromUrl.ts
  packages/web/src/styles/globals.css
  packages/web/src/types/type.ts
Labels: 📬 API, ✨ Feature, gpt review

#67 Style: 팀 리스트 카드 조정
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/dashboard/team-list/state.ts
  packages/web/src/containers/team-list/TeamListWrapper.tsx
  packages/web/src/containers/team-list/teamList.module.css
Labels: 🎨 Html&css

#68 Feature/chat
  packages/web/src/apis/chat.ts
  packages/web/src/apis/createChat.ts
  packages/web/src/apis/getChat.ts
  packages/web/src/apis/getChatByClient.ts
  packages/web/src/apis/getGame.ts
  packages/web/src/apis/getPrevChatByClient.ts
  packages/web/src/app/@modal/(.)profile/[id]/page.tsx
  packages/web/src/app/dashboard/chat/[roomNumber]/page.tsx
  packages/web/src/app/dashboard/chat/layout.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/profile/[id]/page.tsx
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/game/GameSelectBox.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalGames.tsx
  packages/web/src/containers/additional-details/AdditionalOptions.tsx
  packages/web/src/containers/chat-room/ChatLogList.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/MessageItem.tsx
  packages/web/src/containers/profile-modal/createChatButton.tsx
  packages/web/src/containers/profile-modal/profile.module.css
  packages/web/src/containers/profile-modal/profileContainer.tsx
  packages/web/src/containers/profile-modal/profileLayout.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/SelectBoxContainer.tsx
  packages/web/src/lib/calculateAge.ts
  packages/web/src/lib/fetchGamesData.ts
  packages/web/src/lib/getAllProfileData.ts
  packages/web/src/lib/getChatroomData.ts
  packages/web/src/lib/getRoomDataByClient.ts
  packages/web/src/middleware.ts
  packages/web/src/store/gameStore.ts
  packages/web/src/types/ChatType.ts
  packages/web/src/types/type.ts
Labels: 📬 API, ✨ Feature

#74 Feature/search user
  packages/ui/src/components/Inputs/SearchInput.tsx
  packages/ui/tsconfig.tsbuildinfo
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/search/SearchBox.tsx
  packages/web/src/components/search/searchbox.module.css
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/SearchBox.tsx
Labels: 📬 API, ✨ Feature, gpt review

#76 Feature/toast
  package.json
  packages/web/package.json
  packages/web/src/apis/createChat.ts
  packages/web/src/apis/createUser.ts
  packages/web/src/app/layout.tsx
  packages/web/src/components/DatePicker/DatePicker.tsx
  packages/web/src/components/Toast/toast.module.css
  packages/web/src/components/Toast/toast.tsx
  packages/web/src/components/game/GameSelectBox.tsx
  packages/web/src/components/modal/modalClient.tsx
  packages/web/src/components/providers/modal-provider.tsx
  packages/web/src/components/ui/calendar.tsx
  packages/web/src/containers/additional-details/AdditionalDetailsLayout.tsx
  packages/web/src/containers/additional-details/AdditionalGames.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/additional-details/AdditionalOptions.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/store/gameStore.ts
  packages/web/src/styles/globals.css
  yarn.lock
Labels: 📬 API, ✨ Feature

#78 Feature/queue
  packages/web/src/app/dashboard/queue/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/containers/queue/BackGroundTextBox.tsx
  packages/web/src/containers/queue/QueueButton.tsx
  packages/web/src/containers/queue/QueueCard.tsx
  packages/web/src/containers/queue/QueueCardWrapper.tsx
  packages/web/src/containers/queue/QueueDescription.tsx
  packages/web/src/containers/queue/QueueHeader.tsx
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/containers/queue/queue.module.css
  packages/web/src/styles/loader.css
Labels: 🎨 Html&css

#80 Feature/swipe
  packages/ui/src/components/Icons/GameIcon.tsx
  packages/ui/src/components/Icons/GameIcon2.tsx
  packages/ui/src/components/Icons/GameIcon3.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/Inputs/Input.css
  packages/ui/src/components/Inputs/Textarea.stories.ts
  packages/ui/src/components/Inputs/Textarea.tsx
  packages/ui/src/components/TeamCard/JoinButton.tsx
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/src/apis/actionSwipe.ts
  packages/web/src/apis/createChat.ts
  packages/web/src/apis/data.ts
  packages/web/src/apis/getGame.ts
  packages/web/src/apis/getMbti.ts
  packages/web/src/apis/getProfileByUuid.ts
  packages/web/src/apis/getSwipe.ts
  packages/web/src/app/@modal/(.)profile/[id]/page.tsx
  packages/web/src/app/dashboard/queue/page.tsx
  packages/web/src/app/dashboard/swipe/page.tsx
  packages/web/src/components/Background/BackGroundTextBox.tsx
  packages/web/src/components/Background/Background.module.css
  packages/web/src/components/Card/SwipeCard.tsx
  packages/web/src/components/Card/card.module.css
  packages/web/src/components/Friends/FriendsWrapper.tsx
  packages/web/src/components/Navbar/NavHeader.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/navbar.module.css
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/components/modal/modalClient.tsx
  packages/web/src/components/search/SearchBox.tsx
  packages/web/src/containers/additional-details/AdditionalMBTI.tsx
  packages/web/src/containers/queue/QueueHeader.tsx
  packages/web/src/containers/queue/queue.module.css
  packages/web/src/containers/swipe/BackCard.tsx
  packages/web/src/containers/swipe/FrontCard.tsx
  packages/web/src/containers/swipe/RefreshButton.tsx
  packages/web/src/containers/swipe/SwipeCardWrapper.tsx
  packages/web/src/containers/swipe/SwipeForm.tsx
  packages/web/src/containers/swipe/swipe.module.css
  packages/web/src/containers/team-list/CreateButton.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/lib/calculateLevel.ts
  packages/web/src/lib/fetchGamesData.ts
  packages/web/src/store/defaultState.ts
  packages/web/src/styles/globals.css
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#82 Feature/queue
  packages/ui/src/components/Icons/GameIcon4.tsx
  packages/ui/src/components/Icons/PlayIcon.tsx
  packages/ui/src/components/Icons/RefreshIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.tsbuildinfo
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/apis/actionQueue.ts
  packages/web/src/apis/getProfileImage.ts
  packages/web/src/app/dashboard/queue/layout.tsx
  packages/web/src/app/dashboard/queue/page.tsx
  packages/web/src/app/dashboard/queue/start/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/components/Card/FrontCard.tsx
  packages/web/src/components/Card/card.module.css
  packages/web/src/components/Sidebar/ChatRightSide.tsx
  packages/web/src/components/Toast/toast-provider.tsx
  packages/web/src/containers/queue/GameSelectBox.tsx
  packages/web/src/containers/queue/QueueButton.tsx
  packages/web/src/containers/queue/QueueCard.tsx
  packages/web/src/containers/queue/QueueCardWrapper.tsx
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/containers/queue/queue.module.css
  packages/web/src/containers/swipe/SwipeCardWrapper.tsx
  packages/web/src/containers/swipe/swipe.module.css
  packages/web/src/hooks/useSSEMatchingConnection.ts
  yarn.lock
Labels: ✨ Feature

#84 Fix: 토큰 수정 및 콘텐트타입 추가
  packages/web/src/apis/actionQueue.ts
  packages/web/src/app/dashboard/queue/start/page.tsx
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/hooks/useSSEMatchingConnection.ts
Labels: 🐞 BugFix

#85 Fix: sse 연결 수정
  packages/web/src/app/dashboard/queue/start/page.tsx
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/hooks/useSSEMatchingConnection.ts
Labels: 🐞 BugFix

#87 Feature/style
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  packages/web/src/components/Navbar/Alarm.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/NavbarItem.tsx
  packages/web/src/components/Navbar/navbar.module.css
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/styles/colors.css
  packages/web/src/styles/globals.css
Labels: 🎨 Html&css

#88 Feat : sse 연결 및 실시간 알림 수신
  package.json
  packages/ui/tsconfig.tsbuildinfo
  packages/web/package.json
  packages/web/src/app/dashboard/alarm/page.tsx
  packages/web/src/types/event-source-polyfill.d.ts
Labels: ✨ Feature

#92 Feat: 친구 목록 페이지 및 요청 목록 페이지
  .yarn/sdks/typescript/package.json
  package.json
  packages/web/src/apis/getFriends.ts
  packages/web/src/apis/updateFriends.ts
  packages/web/src/app/dashboard/friends-list/page.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/profile/[id]/page.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/containers/friends-list/FriendListTable.tsx
  packages/web/src/containers/friends-list/FriendTabs.tsx
  packages/web/src/containers/friends-list/Search.tsx
  packages/web/src/containers/friends-list/button/MenuButton.tsx
  packages/web/src/containers/friends-list/button/MessageButton.tsx
  packages/web/src/containers/friends-list/button/message-svgrepo-com.png
  packages/web/src/containers/friends-list/button/three-dots-vertical-svgrepo-com.png
  packages/web/src/containers/my-page/ProfileImageUpload.tsx
  packages/web/src/lib/friendData.ts
  packages/web/src/lib/getFriendsData.ts
  yarn.lock
Labels: 📬 API, 🎨 Html&css

#93 Feature/style
  packages/ui/src/components/TeamCard/JoinButton.tsx
  packages/ui/tsconfig.tsbuildinfo
  packages/web/public/images/bg-image.png
  packages/web/src/apis/createChat.ts
  packages/web/src/apis/getChat.ts
  packages/web/src/apis/getChatByClient.ts
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/queue/layout.tsx
  packages/web/src/app/dashboard/queue/page.tsx
  packages/web/src/app/dashboard/queue/start/page.tsx
  packages/web/src/app/dashboard/swipe/page.tsx
  packages/web/src/app/dashboard/team-list/page.tsx
  packages/web/src/app/page.tsx
  packages/web/src/components/Background/BackGroundTextBox.tsx
  packages/web/src/components/Background/Background.module.css
  packages/web/src/components/FloatButton/GoToDashboard.tsx
  packages/web/src/components/FloatButton/floatbutton.module.css
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Friends/FriendsWrapper.tsx
  packages/web/src/components/Navbar/Alarm.tsx
  packages/web/src/components/Navbar/NavHeader.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Navbar/NavbarItem.tsx
  packages/web/src/components/Navbar/TitleHeader.tsx
  packages/web/src/components/Navbar/navbar.module.css
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/components/Sidebar/Sidebar.tsx
  packages/web/src/components/search/SearchBox.tsx
  packages/web/src/components/search/searchbox.module.css
  packages/web/src/containers/chat/GroupChatHeader.tsx
  packages/web/src/containers/chat/GroupMessageItem.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/MessageItem.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/containers/team-list/CreateButton.tsx
  packages/web/src/containers/team-list/GameSelectBox.tsx
  packages/web/src/containers/team-list/SelectBoxContainer.tsx
  packages/web/src/containers/team-list/SubSelectBox.tsx
  packages/web/src/containers/team-list/SubSelectButtons.tsx
  packages/web/src/containers/team-list/TeamBox.tsx
  packages/web/src/containers/team-list/TeamListWrapper.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/hooks/useSSEMatchingConnection.ts
  packages/web/src/lib/getRoomDataByClient.ts
  packages/web/src/styles/colors.css
  packages/web/src/styles/globals.css
Labels: 🔨 Refactor, 🎨 Html&css

#94 Feat : 실시간 알림 수신
  packages/web/src/apis/actionAlarm.ts
  packages/web/src/apis/getAlarms.ts
  packages/web/src/apis/requestAlarm.ts
  packages/web/src/app/dashboard/alarm/page.tsx
  packages/web/src/components/Navbar/Alarm.tsx
  packages/web/src/components/Navbar/alarm.module.css
  packages/web/src/containers/alarm/AlarmListContainer.tsx
  packages/web/src/containers/alarm/AlarmListItem.tsx
  packages/web/src/containers/alarm/ApproveButton.tsx
  packages/web/src/containers/alarm/RejectButton.tsx
  packages/web/src/containers/alarm/SseConnection.tsx
  packages/web/src/containers/alarm/SseService.tsx
  packages/web/src/containers/alarm/useAlarmData.ts
  packages/web/src/types/type.ts
  yarn.lock
Labels: ✨ Feature

#95 Feature/chat
  package.json
  packages/ui/tsconfig.tsbuildinfo
  packages/web/src/apis/actionGroupChat.ts
  packages/web/src/apis/actionQueue.ts
  packages/web/src/apis/createChat.ts
  packages/web/src/apis/getFriends.ts
  packages/web/src/app/dashboard/chat/page.tsx
  packages/web/src/app/dashboard/friends-list/page.tsx
  packages/web/src/app/dashboard/queue/page.tsx
  packages/web/src/app/dashboard/queue/start/page.tsx
  packages/web/src/app/dashboard/swipe/page.tsx
  packages/web/src/app/layout.tsx
  packages/web/src/app/page.tsx
  packages/web/src/app/profile/[id]/page.tsx
  packages/web/src/components/Card/FrontCard.tsx
  packages/web/src/components/FloatButton/GoToDashboard.tsx
  packages/web/src/components/FloatButton/floatbutton.module.css
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/components/Friends/FriendsWrapper.tsx
  packages/web/src/components/Navbar/Navbar.tsx
  packages/web/src/components/Sidebar/ChatRightSide.tsx
  packages/web/src/components/Sidebar/RightSidebar.tsx
  packages/web/src/components/Sidebar/Sidebar.module.css
  packages/web/src/containers/chat-room/ChatLogList.tsx
  packages/web/src/containers/chat-room/GroupChatLogList.tsx
  packages/web/src/containers/chat-room/GroupMessageGroup.tsx
  packages/web/src/containers/chat-room/chat.module.css
  packages/web/src/containers/chat/ChatHeader.tsx
  packages/web/src/containers/chat/ChatInputBox.tsx
  packages/web/src/containers/chat/ChatRoomContainer.tsx
  packages/web/src/containers/chat/GroupChatHeader.tsx
  packages/web/src/containers/chat/GroupChatInputBox.tsx
  packages/web/src/containers/chat/GroupChatRoomContainer.tsx
  packages/web/src/containers/chat/MessageContainer.tsx
  packages/web/src/containers/chat/chat.module.css
  packages/web/src/containers/friends-list/FriendListTable.tsx
  packages/web/src/containers/friends-list/FriendTabs.tsx
  packages/web/src/containers/main/CTA.tsx
  packages/web/src/containers/main/Footer.tsx
  packages/web/src/containers/main/TestimonialsSlider.tsx
  packages/web/src/containers/main/mainLayout.tsx
  packages/web/src/containers/queue/QueueLayout.tsx
  packages/web/src/containers/swipe/RefreshButton.tsx
  packages/web/src/containers/swipe/swipe.module.css
  packages/web/src/containers/team-list/TeamBox.tsx
  packages/web/src/containers/team-list/teamList.module.css
  packages/web/src/hooks/useSSEMatchingConnection.ts
  packages/web/src/lib/getQueueDataByClient.ts
  packages/web/src/lib/getRoomDataByClient.ts
  packages/web/src/lib/getUserData.ts
  packages/web/src/store/voiceRoomStore.ts
  packages/web/src/styles/colors.css
  packages/web/src/styles/globals.css
  yarn.lock
Labels: 📬 API, ✨ Feature
