Repository 6-dreaming-stars/space-star-front-monorepo, pull requests merged in 2024-07, with the labels that each got.

#97 feat: 마이페이지 구현
  packages/ui/tsconfig.tsbuildinfo
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/dashboard/my-page/profile/page.tsx
Labels: 🎨 Html&css

#98 Feature/more
  packages/web/src/apis/actionSwipe.ts
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/components/Navbar/Alarm.tsx
  packages/web/src/containers/dashboard/Card.tsx
  packages/web/src/containers/dashboard/Games.tsx
  packages/web/src/containers/dashboard/UserProfile.tsx
  packages/web/src/containers/dashboard/components.tsx
  packages/web/src/containers/dashboard/dashboard.module.css
  packages/web/src/containers/swipe/SwipeCardWrapper.tsx
  packages/web/src/containers/team-list/TeamBox.tsx
Labels: 🔨 Refactor, ✨ Feature

#101 Feature/more
  packages/web/src/app/dashboard/layout.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/containers/chat-room/GroupMessageGroup.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/chat-room/chat.module.css
  packages/web/src/containers/dashboard/Games.tsx
  packages/web/src/containers/dashboard/dashboard.module.css
  packages/web/src/containers/team-list/TeamBox.tsx
  packages/web/src/lib/getRoomDataByClient.ts
  packages/web/src/lib/getUserData.ts
  packages/web/src/styles/colors.css
Labels: 📬 API, ✨ Feature

#102 Feature/more
  packages/web/src/apis/actionAlarm.ts
  packages/web/src/apis/getAlarms.ts
  packages/web/src/app/@modal/(.)profile/[id]/page.tsx
  packages/web/src/app/dashboard/my-page/page.tsx
  packages/web/src/app/dashboard/page.tsx
  packages/web/src/components/Friends/FriendsList.tsx
  packages/web/src/containers/additional-info/AdditionalInfoForm.tsx
  packages/web/src/containers/alarm/AlarmListItem.tsx
  packages/web/src/containers/alarm/SseConnection.tsx
  packages/web/src/containers/alarm/SseService.tsx
  packages/web/src/containers/chat-room/GroupMessageGroup.tsx
  packages/web/src/containers/chat-room/MessageGroup.tsx
  packages/web/src/containers/chat/GroupChatHeader.tsx
  packages/web/src/containers/chat/GroupMessageItem.tsx
  packages/web/src/containers/dashboard/components.tsx
  packages/web/src/containers/friends-list/Search.tsx
  packages/web/src/containers/main/CTA.tsx
  packages/web/src/containers/main/TestimonialsSlider.tsx
  packages/web/src/containers/main/mainLayout.tsx
  packages/web/src/containers/my-page/ProfileImageUpload.tsx
  packages/web/src/containers/my-page/profileButton.tsx
  packages/web/src/containers/team-list/SubSelectButtons.tsx
  packages/web/src/containers/team-list/TeamBox.tsx
  packages/web/src/styles/globals.css
Labels: ✨ Feature

#103 Feat : 매칭 요청 수락 시 1:1 채팅방 생성
  packages/web/src/apis/requestAlarm.ts
  packages/web/src/containers/alarm/AlarmListItem.tsx
  packages/web/src/containers/alarm/ApproveButton.tsx
  packages/web/src/containers/alarm/RejectButton.tsx
  packages/web/src/containers/alarm/SseConnection.tsx
  yarn.lock
Labels: ✨ Feature

#106 Fix: fixed image
  packages/web/next.config.mjs
  packages/web/src/containers/chat-room/GroupMessageGroup.tsx
Labels: 🐞 BugFix
